### PR TITLE
Config file created

### PR DESCRIPTION
**Pull request by Trle94**
Place following file at this location:
./application/config/recaptcha.php

### CODE REVIEW

**Comment by mehdibo** [comment]
Thanks for the edits.
I don't really like the idea of adding the JS file with the box in the body, and it's not that hard to add it in a header file.
The other edit is good, I was planning to add a config file and didn't have the time to do so, but you only added the config file without implementing it in the library.
The config file also has some unnecessary comments, you should use PHPDOC style to comment on the config file.

**Comment by Trle94** [comment]
I apologize for mistakes, I would fix them if you do not have time, just wanted to make life easier for everyone and to contribute..

**Comment by mehdibo** [comment]
No need to apologise, you can make the changes and re-submit them.
If you don't, I'll try to make them in the coming days.

**Comment by mehdibo** [comment]
I've updated the library (finally) with the config file feature.
Any future suggestions/contributions are welcome!

**Pull request closed without merging**
